### ISSUE TITLE
Option for indexing a single package

### ISSUE THREAD

**Issue by RyanGlScott** [bgamari/hoogle-index#8]
I like `hoogle-index`, but I don't quite have the storage space needed to index every single Haskell library I have installed. Would it be possible to add a command-line parameter to only index a single package? Perhaps something akin to `hoogle -single <name-of-package>` (for filtering out a package from the databases) or `hoogle -single <directory>` (for specifying the project directory to call `cabal haddock` in).

**Comment by bgamari** [comment]
Sounds possible to me. I'll have a look tomorrow.

**Comment by RyanGlScott** [comment]
Closing stale issue.
